modLoader="javafml"
loaderVersion="[47,)"
license="MIT"

[[mods]]
modId="mcextractors"
version="1.0.0"
displayName="MCExtractors"
authors="Jikai"
description='''
MCExtractors adds specialized extraction machines to Minecraft.
Extract iron nuggets from cobblestone with the Iron Extractor!
'''

[[dependencies.mcextractors]]
    modId="forge"
    mandatory=true
    versionRange="[47,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.mcextractors]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1,1.21)"
    ordering="NONE"
    side="BOTH"
